export {default as keys} from './keys'
export {default as texts} from './texts'
export {default as strings} from './strings'
export {default as result} from './result'
export {default as vars} from './variables'