name: Build Vue App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install npm
        run: npm install
      - name: Clean cache
        run: npm cache clean --force
      - name: npx browserslist@latest --update-db
        run: npx browserslist@latest --update-db
      - name: Build web application
        run: npm run build
