name: Render
on: push
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: johnbeynon/render-deploy-action@0.0.8
        with:
          api-key: rnd_6FfZjiNqzRyBHUcVr0snQNRMxpb9
          service-id: srv-chqor767avjb90mhnjrg
